In [1]:
import numpy as np

In [2]:
L = [1, 2, 3]

In [3]:
A = np.array([1, 2, 3])

In [4]:
for e in L:
    print(e)

1
2
3


In [5]:
for e in A:
    print(e)

1
2
3


In [6]:
L.append(4)

In [7]:
L

[1, 2, 3, 4]

In [9]:
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [10]:
L = L + [5]

In [11]:
L

[1, 2, 3, 4, 5]

In [12]:
A = A + [4, 5]

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [13]:
L2 = []

for e in L:
    L2.append(e+e)

L2

[2, 4, 6, 8, 10]

In [14]:
A + A

array([2, 4, 6])

In [15]:
2 * A

array([2, 4, 6])

In [16]:
2 * L

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [17]:
L ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [18]:
L2 = []

for e in L:
    L2.append(e ** 2)

L2

[1, 4, 9, 16, 25]

In [19]:
A ** 2

array([1, 4, 9], dtype=int32)

In [20]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [21]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [22]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])