In [1]:
import numpy as np

In [2]:
Z = np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
Z = np.zeros((10,10))
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
O = np.ones((10,10))
O

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [6]:
R = np.random.random((10,10))
R

array([[0.42262864, 0.70552789, 0.07319445, 0.49971313, 0.81807746,
        0.27363173, 0.58467259, 0.62515372, 0.34429983, 0.74942103],
       [0.76131329, 0.13541732, 0.79203175, 0.85797407, 0.94966086,
        0.09267211, 0.12533715, 0.35673433, 0.71790234, 0.83079673],
       [0.98368271, 0.03260394, 0.5740722 , 0.32142836, 0.96289055,
        0.51784143, 0.08582775, 0.4220599 , 0.56108244, 0.07724984],
       [0.1090547 , 0.96220576, 0.21301972, 0.02558891, 0.83141747,
        0.29345354, 0.82754868, 0.7648357 , 0.38433954, 0.59644307],
       [0.62078962, 0.80463864, 0.1171422 , 0.94903841, 0.96897702,
        0.55408783, 0.90356431, 0.97779274, 0.30172781, 0.27968361],
       [0.39923285, 0.72251738, 0.89064415, 0.55834189, 0.81247949,
        0.28091991, 0.17780032, 0.10795787, 0.08917241, 0.46675717],
       [0.96989704, 0.68446505, 0.79806837, 0.81123028, 0.23604074,
        0.8510054 , 0.84925613, 0.35692306, 0.0949063 , 0.1083466 ],
       [0.56230557, 0.45890702, 0.2257783

In [8]:
G = np.random.randn(10,10)
G

array([[ 0.44512511, -0.66844806,  0.44195839, -1.22928506, -0.25704092,
         1.13655952, -0.03769245,  0.24456889,  0.09354856,  0.6073773 ],
       [-0.38254341, -0.49322801,  0.42611203,  0.47056105, -0.44610743,
         2.08681889,  0.23295941,  0.17970445,  0.04009141, -0.23417042],
       [ 0.16635934,  1.34929763, -2.73431613, -0.66946769, -0.66218298,
        -0.33991482, -0.00541775, -2.14970911,  0.16410628,  0.4710826 ],
       [-0.98585383,  0.68918163, -0.5545064 , -0.80164016, -1.75334523,
        -0.38937096, -0.61044074,  0.66284478,  0.33848711,  0.07554715],
       [ 1.96526393,  0.47492782, -1.64053144,  1.48913063, -0.09263715,
         0.02489578,  0.00766158, -0.24347486,  1.13192081,  0.6900629 ],
       [ 0.5659158 ,  0.77678369,  1.10429376, -1.01799026,  1.77114542,
         0.65554494,  0.2699265 ,  0.75409734,  0.77031658,  2.87278708],
       [ 1.1911013 ,  0.3285783 , -0.29619776,  1.16223087,  0.44088186,
         1.47187215, -1.30632047,  0.91388123

In [9]:
G.mean()

0.13201644604613344

In [10]:
G.var()

0.9822016521720088