**Matrix products**:

- Matrix multiplication.
- Requirement: inner dimensions must match.
- If we have $A$ of size (2,3) and $B$ of size (3,3):
	- We can multiply $AB$ (inner dimension is 3).
	- We cannot multiply $BA$.
- Matrix multiplication definition:
$$
C(i,j) = \displaystyle\sum_{k=1}^{K} A(i,k) B(k,j)
$$
- The $(i,j)$-th entry of $C$ is the dot product of row $A(i,:)$ and column $B(:,j)$.
- In Numpy, `C = A.dot(B)`.



- It is very natural to want to do $C(i,j) = A(i,j) \cdot B(i,j)$, i. e., the element-wise multiplication.
	- We saw that asterisk does this for vectors.
	- It also works with 2-D arrays, and >2-D arrays.
	- Both arrays must have the same size.
- It is odd that there is no well-defined mathematical symbol for it.
	- Shows up a few times in deep learning: $\otimes$ or $\odot$

In [1]:
import numpy as np

In [2]:
A = np.array([[1,2],[3,4]])

In [3]:
Ainv = np.linalg.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [4]:
Ainv.dot(A)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [5]:
A.dot(Ainv)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [6]:
np.linalg.det(A)

-2.0000000000000004

In [7]:
np.diag(A)

array([1, 4])

In [8]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

**Outer/Inner product**:

- Outer product: $C(i,j) = A(i) B(j)$
	- Ex.: $\textrm{Cov}(X,Y) = \textrm{E}\big[(X-\textrm{E}[X])(Y-\textrm{E}[Y])^T\big] \approx \displaystyle\frac{1}{N-1}\sum_{n=1}^N (x_n - \bar x)(y_n - \bar y)$.
    - More [here](https://en.wikipedia.org/wiki/Outer_product).
- Inner product: $\displaystyle\sum_i A(i)B(i)$.
	- Same as dot product.

In [9]:
a = np.array([1,2])
b = np.array([3,4])

In [10]:
np.outer(a,b)

array([[3, 4],
       [6, 8]])

In [11]:
np.inner(a,b)

11

In [12]:
np.inner(a,b) == a.dot(b)

True

In [14]:
np.diag(A).sum() # trace of a matrix

5

In [15]:
np.trace(A)

5

**Eigenvalues & eigenvectors**:

- `eigenvals, eigenvecs = np.linalg.eig(C)`
- `eigenvals, eigenvecs = np.linalg.eigh(C)`
	- For <u>symmetric</u> and Hermitian matrices.
	- Symmetric means $A = A^T$.
	- Hermitian means $A = A^H$ ($A^H$ is the conjugate transpose of $A$).
		- More [here](https://en.wikipedia.org/wiki/Conjugate_transpose).

In [16]:
X = np.random.randn(100,3) # 100 samples, 3 features

In [18]:
cov = np.cov(X.T)
cov

array([[0.95150313, 0.15249746, 0.13819883],
       [0.15249746, 1.22166483, 0.04738017],
       [0.13819883, 0.04738017, 1.11287563]])

In [19]:
np.linalg.eigh(cov) # covariance matrix is symmetric

(array([0.83794381, 1.10836113, 1.33973865]),
 array([[ 0.87230706,  0.16644393, -0.45975734],
        [-0.29888875, -0.56264191, -0.77077856],
        [-0.38697016,  0.80977188, -0.4410483 ]]))

In [20]:
np.linalg.eig(cov)

(array([0.83794381, 1.33973865, 1.10836113]),
 array([[-0.87230706,  0.45975734,  0.16644393],
        [ 0.29888875,  0.77077856, -0.56264191],
        [ 0.38697016,  0.4410483 ,  0.80977188]]))